#!/bin/sh

echo "Ready to start Nginx, waiting for php-fpm on 127.0.0.1:9000..."
# Wait for php-fpm to be ready
until nc -z 127.0.0.1 9000; do
    echo "Wait for php-fpm..."
    sleep 1
done
echo "php-fpm is up! Starting nginx."

exec nginx -c /etc/nginx/nginx.conf
